// Foreign Key Relationships - Validated
Ref: fi_valuation_entry.lastmod_by > ze_mitarb.ma_id
Ref: cal_eventdates.event > cal_event.id
Ref: cal_jobassign.event > cal_event.id
Ref: cal_resourceassign.resource > cal_resource.id
Ref: nt_payload.message_id > nt_message.id
Ref: nt_queue.user_id > ze_mitarb.ma_id
Ref: nt_queue.user_cc > ze_mitarb.ma_id
Ref: nt_message.origin_user > ze_mitarb.ma_id
Ref: nt_forward.orig_user > ze_mitarb.ma_id
Ref: nt_queue.message_id > nt_message.id
Ref: nt_forward.fwd_user > ze_mitarb.ma_id
Ref: nt_filter.scope_id > ze_mitarb.ma_id
Ref: nt_queue.fw > ze_mitarb.ma_id
Ref: nt_message.responsible_user > ze_mitarb.ma_id
Ref: nt_message.job_id > ze_job.job_id
Ref: nt_queue.alert_id > in_alert.id
Ref: in_alert.user_id > ze_mitarb.ma_id
Ref: oauth2_access_token.user_id > ze_mitarb.ma_id
Ref: oauth_info.user_id > ze_mitarb.ma_id
Ref: ma_category.parentId > ma_category.id
Ref: ma_entry.category > ma_category.id
Ref: me_memo.changedby > ze_mitarb.ma_id
Ref: ne_comments.newsid > ne_news.id
Ref: ne_comments.addedby > ze_mitarb.ma_id
Ref: ne_news.addedby > ze_mitarb.ma_id
Ref: ne_news.changedby > ze_mitarb.ma_id
Ref: ne_viewed.user_id > ze_mitarb.ma_id
Ref: ne_viewed.news_id > ne_news.id
Ref: queue_task.user > ze_mitarb.ma_id
Ref: queue_task_params.key_id > queue_task.id
Ref: re_reporting.user > ze_mitarb.ma_id
Ref: re_field.reporting_id > re_reporting.id
Ref: re_filter.reporting_id > re_reporting.id
Ref: sc_orders.jobid > ze_job.job_id
Ref: sync_key_custom.key_id > sync_key.id
Ref: sync_key_multiple.sync_key > sync_key.id
Ref: sync_queue.sync_key > sync_key.id
Ref: sync_event.sync_key > sync_key.id
Ref: sync_adapter_config.sync_adapter_id > sync_adapter.id
Ref: sync_state.sync_adapter_id > sync_adapter.id
Ref: sync_key.sync_adapter_id > sync_adapter.id
Ref: crm_sticker.user > ze_mitarb.ma_id
Ref: crm_sticker.category > crm_category.id
Ref: crm_stuck.sticker > crm_sticker.id
Ref: crm_stuck.da_id > da_firma.id
Ref: crm_stuck.da_id > da_person.id
Ref: crm_blog.user > ze_mitarb.ma_id
Ref: crm_blog.company > da_firma.id
Ref: crm_blog.da_id > da_firma.id
Ref: crm_blog.da_id > da_person.id
Ref: crm_channel.type_id > crm_channel_type.id
Ref: crm_channel.company_id > da_firma.id
Ref: comm_message.sender > ze_mitarb.ma_id
Ref: comm_message.mail_id > comm_mail.id
Ref: comm_reaction.message_id > comm_message.id
Ref: comm_reaction.user_id > ze_mitarb.ma_id
Ref: comm_readby.message_id > comm_message.id
Ref: comm_readby.emp_id > ze_mitarb.ma_id
Ref: comm_mail_copyrecipient.mail_id > comm_mail.id
Ref: comm_mail_contact.contact > da_person.id
Ref: comm_mail_copyrecipient.contact_id > comm_mail_contact.id
Ref: comm_mail_recipient.contact_id > comm_mail_contact.id
Ref: comm_mail_recipient.mail_id > comm_mail.id
Ref: comm_mail_references.mail_id > comm_mail.id
Ref: comm_attachment.message_id > comm_message.id
Ref: comm_comment_recipient.message_id > comm_message.id
Ref: comm_comment_recipient.employee_id > ze_mitarb.ma_id
Ref: comm_connection.message_id > comm_message.id
Ref: comm_connection.data_id > da_person.id
Ref: comm_connection.data_id > da_firma.id
Ref: comm_connection.data_id > ze_bereich.ber_id
Ref: comm_connection.data_id > ze_job.job_id
Ref: comm_connection.data_id > pm_workpackages.id
Ref: comm_connection.data_id > fi_invoice.id
Ref: cockpit_lunch_position.tenant > in_tenant.id
Ref: co_ansatz.ma > ze_mitarb.ma_id
Ref: api_user_access_token.user_id > ze_mitarb.ma_id
Ref: cal_ctag.calid > cal_category.id
Ref: cal_eventassign.event > cal_event.id
Ref: cal_eventassign.job_id > ze_job.job_id
Ref: cal_share.event_id > cal_event.id
Ref: cal_share.user_id > ze_mitarb.ma_id
Ref: cal_share.group_id > ze_abtlg.abt_id
Ref: cal_event.owner > ze_mitarb.ma_id
Ref: cal_event.category > cal_category.id
Ref: cal_resourceassign.event > cal_event.id
Ref: cal_jobassign.job > ze_job.job_id
Ref: cal_jobassign.job > ze_bereich.ber_id
Ref: cal_jobassign.job > ze_kunde.kd_id
Ref: cal_event.repeatrule > cal_repeatrule.id
Ref: nl_adressat.mailing > nl_mailing.id
Ref: nl_adressat.person > da_person.id
Ref: nl_content.mailing > nl_mailing.id
Ref: nl_file.mailing > nl_mailing.id
Ref: nl_mailing.newsletter > nl_newsletter.id
Ref: nl_mailing.author > da_person.id
Ref: nl_newsletter.template > nl_template.id
Ref: nl_newsletter.creator > da_person.id
Ref: nl_newsletter.sticker > crm_sticker.id
Ref: md_data.employee_id > ze_mitarb.ma_id
Ref: md_metadata.md_data_id > md_data.id
Ref: md_data.mediatype > md_mediatypes.id
Ref: md_data.job_id > ze_job.job_id
Ref: md_mediatype_fields.template > md_mediatypes.id
Ref: internet_account_configs.key_id > internet_account.id
Ref: doc_art.filetype > doc_filetype.id
Ref: doc_meta.document > doc_document.id
Ref: doc_ablage.filesystem > in_filesystem.id
Ref: doc_meta.type > doc_metatype.id
Ref: doc_document.filetype > doc_filetype.id
Ref: doc_document.ablage > doc_ablage.id
Ref: doc_document.art > doc_art.id
Ref: doc_document.autor > ze_mitarb.ma_id
Ref: doc_document.job > ze_job.job_id
Ref: doc_metatype.da_type > da_firma.id
Ref: doc_metatype.da_type > da_person.id
Ref: in_alert.data_id > cal_event.id
Ref: in_alert.data_id > comm_message.id
Ref: in_custom_fields.data_id > fi_bordereau.id
Ref: in_custom_fields.data_id > fi_invoice.id
Ref: in_custom_fields.data_id > ze_job.job_id
Ref: in_custom_fields.data_id > ze_mitarb.ma_id
Ref: in_authlog.loggedin_user > ze_mitarb.ma_id
Ref: in_authlog.affected_user > ze_mitarb.ma_id
Ref: in_content_connection.data_id > ze_job.job_id
Ref: in_content_connection.data_id > fi_invoice.id
Ref: in_content_connection.data_id > fi_kv.id
Ref: in_aias.userid > ze_mitarb.ma_id
Ref: in_config.user > ze_mitarb.ma_id
Ref: in_custom_fields.data_id > ze_kunde.kd_id
Ref: in_custom_fields.data_id > fi_kv.id
Ref: in_datalogged.user > ze_mitarb.ma_id
Ref: in_datalogged.dataid > file_base.id
Ref: in_datalogged.dataid > fi_bordereau.id
Ref: in_custom_fields.data_id > ze_bereich.ber_id
Ref: in_datalogged.dataid > ze_kunde.kd_id
Ref: in_datalogged.dataid > da_firma.id
Ref: in_datalogged.dataid > da_person.id
Ref: in_datalogged.dataid > te_tender.id
Ref: in_datalogged.dataid > ze_bereich.ber_id
Ref: in_datalogged.dataid > ze_mitarb.ma_id
Ref: in_datalogged.dataid > doc_document.id
Ref: in_datalogged.dataid > fi_kv.id
Ref: in_datalogged.dataid > fi_invoice.id
Ref: in_datalogged.dataid > job_phase.id
Ref: in_datalogged.dataid > comm_message.id
Ref: in_datalogged.dataid > fi_payment.id
Ref: in_datalogged.dataid > re_reporting.id
Ref: in_datalogged.dataid > crm_sticker.id
Ref: in_datalogged.dataid > ze_job.job_id
Ref: in_datalogged.dataid > pm_workpackages.id
Ref: in_datalogged.dataid > ze_arbeit.arb_id
Ref: in_datalogged.dataid > file_mimetype.id
Ref: in_default_text.tenant > in_tenant.id
Ref: in_filesystem.tenant > in_tenant.id
Ref: in_location.language > in_language.id
Ref: in_location.country > da_country.id
Ref: in_location.numberformat > in_base_format.id
Ref: in_lock.object_id > ze_mitarb.ma_id
Ref: in_lock.object_id > fi_kv.id
Ref: in_lock.object_id > fi_invoice.id
Ref: in_lock.object_id > ze_job.job_id
Ref: in_rate_base.tenant > in_tenant.id
Ref: in_permission.rolle > in_rolle.id
Ref: in_permission_datalogged.role > in_rolle.id
Ref: in_permission_datalogged.user > ze_mitarb.ma_id
Ref: in_permission_pending.rolle > in_rolle.id
Ref: in_permission_pending.modified_by > ze_mitarb.ma_id
Ref: in_rate.base_id > in_rate_base.id
Ref: in_rate.client_id > ze_kunde.kd_id
Ref: in_rate.area_id > ze_bereich.ber_id
Ref: in_rate.task_id > ze_job.job_id
Ref: in_rate_activity.activity > ze_leistg.lei_id
Ref: in_rate_activity.rate > in_rate_base.id
Ref: in_rate_amount.rate_id > in_rate.id
Ref: in_rate_amount.staff_level_id > in_stafflevel.id
Ref: in_rate_cost.rate > in_rate_base.id
Ref: in_rate_cost.cost > fi_kostenart.id
Ref: in_rate_base.parent_id > in_rate_base.id
Ref: in_rate_base.unit_id > fi_leistg_unit.id
Ref: in_setting.client_id > ze_kunde.kd_id
Ref: in_setting.area_id > ze_bereich.ber_id
Ref: in_setting.task_id > ze_job.job_id
Ref: in_staff_hierarchy.employee_id > ze_mitarb.ma_id
Ref: in_staff_hierarchy.supervisor_id > ze_mitarb.ma_id
Ref: in_stafflevel.reference_rate > in_rate_base.id
Ref: in_stafflevel.tenant > in_tenant.id
Ref: in_synclog.adapter_id > sync_adapter.id
Ref: in_team.leader > ze_mitarb.ma_id
Ref: in_team.tenant > in_tenant.id
Ref: in_team_members.team_id > in_team.id
Ref: in_team_members.user_id > ze_mitarb.ma_id
Ref: in_tenant.company > da_firma.id
Ref: in_tenant.location_id > in_location.id
Ref: in_textblock.tenant > in_tenant.id
Ref: in_translate.dataid > fi_tax_code.id
Ref: fi_tax_code.tenant > in_tenant.id
Ref: in_translate.dataid > fi_paymentcondition.id
Ref: in_translate.dataid > ze_leavetype.id
Ref: in_translate.dataid > in_language.id
Ref: in_translate.dataid > pm_kanban_column.id
Ref: in_translate.dataid > job_status.id
Ref: in_translate.dataid > job_responsible_type.id
Ref: in_translate.dataid > fi_grp.id
Ref: in_translate.dataid > fi_leistg_unit.id
Ref: in_translate.dataid > fi_kv_type.id
Ref: in_translate.dataid > ze_abtlg.abt_id
Ref: in_translate.dataid > in_default_text.id
Ref: in_translate.dataid > in_currency.id
Ref: in_translate.dataid > da_country.id
Ref: in_translate.dataid > da_branche.id
Ref: in_translate.dataid > ze_client_category.id
Ref: in_translate.dataid > crm_channel_type.id
Ref: in_translate.dataid > crm_channel.id
Ref: in_translate.dataid > cal_category.id
Ref: in_translate.dataid > time_workplace.id
Ref: in_translate.dataid > in_rate_base.id
Ref: in_translate.dataid > pm_entity.id
Ref: in_translate.dataid > pm_attributes.id
Ref: in_translate.dataid > fi_kostenart.id
Ref: in_translate.dataid > ze_leistg.lei_id
Ref: in_unique.tenant > in_tenant.id
Ref: in_userrolle.user > ze_mitarb.ma_id
Ref: in_rolle.id > in_userrolle.rolle
Ref: in_rolle.id > in_userrolle_pending.rolle
Ref: in_userrolle_pending.user > ze_mitarb.ma_id
Ref: in_userrolle_pending.modified_by > ze_mitarb.ma_id
Ref: in_usersession.user_id > ze_mitarb.ma_id
Ref: in_usersetting.user > ze_mitarb.ma_id
Ref: in_validity_periods.data_id > ze_mitarb.ma_id
Ref: in_validity_periods.data_id > in_stafflevel.id
Ref: file_base.user > ze_mitarb.ma_id
Ref: file_related.file > file_base.id
Ref: file_tags.tag_id > file_tag.id
Ref: file_tags.file_id > file_base.id
Ref: job_attribute.defaultvalue > job_group.id
Ref: job_grouped.job > ze_job.job_id
Ref: job_grouped.attr > job_attribute.id
Ref: job_grouped.jobgroup > job_group.id
Ref: job_phase.job_id > ze_job.job_id
Ref: job_phase.template_id > da_templates.id
Ref: job_responsible.responsible_type_id > job_responsible_type.id
Ref: job_responsible.employee_id > ze_mitarb.ma_id
Ref: job_responsible.job_id > ze_job.job_id
Ref: pm_cc.workpackage_id > pm_workpackages.id
Ref: pm_employee_workload.responsible_id > ze_mitarb.ma_id
Ref: pm_employee_workload.workload_level > pm_workload_level.id
Ref: pm_employee_workload.job_id > ze_job.job_id
Ref: pm_kanban_column.type > pm_kanban_column_type.id
Ref: pm_workload.workpackage > pm_workpackages.id
Ref: pm_workload.responsible_id > ze_mitarb.ma_id
Ref: pm_workpackageattributes.attribute_id > pm_attributes.id
Ref: pm_workpackageattributes.workpackage_id > pm_workpackages.id
Ref: pm_workpackages.parent_id > pm_workpackages.id
Ref: pm_workpackages.job_id > ze_job.job_id
Ref: pm_workpackages.responsible_id > ze_mitarb.ma_id
Ref: pm_workpackages.responsible_id > pm_entity.id
Ref: pm_workpackages.responsible_id > ze_abtlg.abt_id
Ref: pm_workpackages.stafflevel > in_stafflevel.id
Ref: pm_workpackages.lastmod_by > ze_mitarb.ma_id
Ref: pm_workpackages.rate_id > in_rate.id
Ref: pm_workpackages.activity_id > ze_leistg.lei_id
Ref: time_attendance.employee_id > ze_mitarb.ma_id
Ref: time_attendance.lastmod_by > ze_mitarb.ma_id
Ref: time_attendance.closed_by > ze_mitarb.ma_id
Ref: time_attendance_period.attendance_id > time_attendance.id
Ref: time_attendance_workplace.workplace > time_workplace.id
Ref: time_attendance_workplace.attendance_id > time_attendance.id
Ref: tresor_passwort.owner_id > ze_mitarb.ma_id
Ref: tresor_passwort.type_id > tresor_category.id
Ref: tresor_passwort_change.change_id > ze_mitarb.ma_id
Ref: tresor_rights.user_id > ze_mitarb.ma_id
Ref: tresor_rights.password_id > tresor_passwort.id
Ref: tresor_rights.group_id > in_rolle.id
Ref: te_dispatch.tender > te_tender.id
Ref: te_document.parent > te_document.id
Ref: te_offer.dispatch > te_dispatch.id
Ref: te_offer.tender > te_tender.id
Ref: te_offer.file > file_base.id
Ref: te_tender.job_id > ze_job.job_id
Ref: te_tender.bearbeiter > ze_mitarb.ma_id
Ref: te_tender.dispatch > te_dispatch.id
Ref: te_tender.anfrage > te_document.id
Ref: te_tender.auftrag > te_document.id
Ref: te_tender.ka > fi_kostenart.id
Ref: ze_abtlg.division_id > ze_division.id
Ref: ze_arbeit.job_id > ze_job.job_id
Ref: ze_arbeit.tenant > in_tenant.id
Ref: ze_arbeit.lei_id > ze_leistg.lei_id
Ref: ze_arbeit.ma_id > ze_mitarb.ma_id
Ref: ze_arbeit.lastmod_by > ze_mitarb.ma_id
Ref: ze_arbeit.created_by > ze_mitarb.ma_id
Ref: ze_arbeit.workpackage_id > pm_workpackages.id
Ref: ze_arbeit.phase_id > job_phase.id
Ref: ze_kunde_team.client > ze_kunde.kd_id
Ref: ze_arbeit.level > in_stafflevel.id
Ref: ze_arbeit.rate > in_rate_base.id
Ref: ze_kunde_team.team > in_team.id
Ref: ze_job.kd_id > ze_kunde.kd_id
Ref: ze_job.ber_id > ze_bereich.ber_id
Ref: ze_job.extern > da_person.id
Ref: ze_job.tenant > in_tenant.id
Ref: ze_job.lastmod_by > ze_mitarb.ma_id
Ref: ze_job.created_by > ze_mitarb.ma_id
Ref: ze_bereich.kd_id > ze_kunde.kd_id
Ref: ze_bereich.tenant > in_tenant.id
Ref: ze_ftbase_location.location_id > in_location.id
Ref: ze_mitazt.ma_id > ze_mitarb.ma_id
Ref: ze_leistg_abtlg.abt_id > ze_abtlg.abt_id
Ref: ze_leistg_abtlg.lei_id > ze_leistg.lei_id
Ref: ze_ftbase_location.ftbase_id > ze_ftbase.id
Ref: ze_ft.base > ze_ftbase.id
Ref: ze_ftbase.country > da_country.id
Ref: ze_ft.country > da_country.id
Ref: ze_offday.employee > ze_mitarb.ma_id
Ref: ze_mitarb.tenant > in_tenant.id
Ref: ze_timeapproval.employee_id > ze_mitarb.ma_id
Ref: ze_timeapproval.approved_by > ze_mitarb.ma_id
Ref: ze_kunde.tenant > in_tenant.id
Ref: ze_ftman.ma_id > ze_mitarb.ma_id
Ref: ze_ftman.changed_by > ze_mitarb.ma_id
Ref: ze_ft_location.location_id > in_location.id
Ref: ze_ft_location.ft_id > ze_ft.id
Ref: ze_urlaub.ma_id > ze_mitarb.ma_id
Ref: ze_worktime.employee > ze_mitarb.ma_id
Ref: ze_worktime.location > in_location.id
Ref: ze_mitarb.abt_id > ze_abtlg.abt_id
Ref: ze_mitarb.level > in_stafflevel.id
Ref: ze_mitarb.vorgesetzter > ze_mitarb.ma_id
Ref: ze_mitarb.location > in_location.id
Ref: da_adresse.da_id > da_person.id
Ref: da_adresse.da_id > da_firma.id
Ref: da_adresse.land > da_country.id
Ref: da_bankdata.da_id > da_person.id
Ref: da_bankdata.da_id > da_firma.id
Ref: da_anschrift.adresse > da_adresse.id
Ref: da_anschrift.person > da_person.id
Ref: da_companyaccount.company > da_firma.id
Ref: da_companyaccount.tenant > in_tenant.id
Ref: da_email.da_id > da_firma.id
Ref: da_email.da_id > da_person.id
Ref: da_data_protection.user_id > ze_mitarb.ma_id
Ref: da_data_protection.contact_id > da_person.id
Ref: da_group_acl.groupid > da_group.id
Ref: da_group_acl.role > in_rolle.id
Ref: da_firma_tenant.firma_id > da_firma.id
Ref: da_firma_tenant.tenant_id > in_tenant.id
Ref: da_vcardextras.da_id > da_firma.id
Ref: da_vcardextras.da_id > da_person.id
Ref: da_suchfeld.gruppe > da_suchgruppe.id
Ref: da_object.user > ze_mitarb.ma_id
Ref: da_kontakt.firma > da_firma.id
Ref: da_kontakt.person > da_person.id
Ref: da_partner.firma > da_firma.id
Ref: da_partner.firma2 > da_firma.id
Ref: da_phone.da_id > da_firma.id
Ref: da_phone.da_id > da_person.id
Ref: da_suchgruppe.parent > da_suchgruppe.id
Ref: da_personuser.person > da_person.id
Ref: fi_workassignment.ma_id > ze_mitarb.ma_id
Ref: fi_taxrates.tenant > in_tenant.id
Ref: fi_taxcodes.tenant > in_tenant.id
Ref: fi_position_percent.cost > fi_kostenart.id
Ref: fi_finance_account.tenant > in_tenant.id
Ref: fi_finance_account.rate_id > in_rate_base.id
Ref: fi_supplier_surcharge.supplier_id > da_firma.id
Ref: fi_supplier_surcharge.cost_id > fi_kostenart.id
Ref: fi_staffexpense.employee_id > ze_mitarb.ma_id
Ref: fi_staffexpense.approval_by > ze_mitarb.ma_id
Ref: fi_recurring_date.invoicepos > fi_invoicepos.id
Ref: fi_recurring_amount.tenant > in_tenant.id
Ref: fi_recurring_amount.job_id > ze_job.job_id
Ref: fi_recurring_amount.cost_id > fi_kostenart.id
Ref: fi_recurring_amount.account > fi_finance_account.id
Ref: fi_recurring_amount.taxcode_id > fi_taxcodes.id
Ref: fi_has_percentage.invoicepos > fi_invoice.id
Ref: fi_has_percentage.cost > fi_kostenart.id
Ref: fi_has_percentage.estimatepos > fi_kvpos.id
Ref: fi_exportjournal.tenant > in_tenant.id
Ref: fi_exportjournal.user_id > ze_mitarb.ma_id
Ref: fi_purchaseorders.job_id > ze_job.job_id
Ref: fi_purchaseorders.supplier_id > da_firma.id
Ref: fi_purchaseorders.cost_id > fi_kostenart.id
Ref: fi_purchaseorders.employee_id > ze_mitarb.ma_id
Ref: fi_purchaseorders.tenant > in_tenant.id
Ref: fi_purchaseorders.taxcode_id > fi_tax_code.id
Ref: fi_purchaseorders.tender_id > te_tender.id
Ref: fi_purchaseorders.file > file_base.id
Ref: fi_position_rate.baserate > in_rate_base.id
Ref: fi_position_rate.stafflevel > in_stafflevel.id
Ref: fi_position_rate.exchangerate > fi_exchangerate.id
Ref: fi_position_rate_multiplier.pos_rate_id > fi_position_rate.id
Ref: fi_invoice_attachment.invoice > fi_invoice.id
Ref: fi_invoice_attachment.attached_id > file_base.id
Ref: fi_paymentcondition.tenant > in_tenant.id
Ref: fi_ledger_entry.ledger > fi_ledger.id
Ref: fi_ledger_entry.taxcode_id > fi_tax_code.id
Ref: fi_ledger_entry.file > file_base.id
Ref: fi_ledger_entry.exported_by > ze_mitarb.ma_id
Ref: fi_payment.invoice > fi_invoice.id
Ref: fi_ledger_period.ledger > fi_ledger.id
Ref: fi_honorar.jobid > ze_job.job_id
Ref: fi_honorar.ka > fi_kostenart.id
Ref: fi_honorar.cost > fi_kostenart.id
Ref: fi_finance_account_cost.cost_id > fi_kostenart.id
Ref: fi_finance_account_cost.account_id > fi_finance_account.id
Ref: fi_kvpos.kvid > fi_kv.id
Ref: fi_kvpos.ka > fi_kostenart.id
Ref: fi_kvpos.grp > fi_grp.id
Ref: fi_kvpos.rate > fi_position_rate.id
Ref: fi_kvpos.tenant > in_tenant.id
Ref: fi_kvpos.migrospos > fi_migrospos.id
Ref: fi_kvpos.taxcode_id > fi_tax_code.id
Ref: fi_kvpos.supplier_id > da_firma.id
Ref: fi_layoutpos.ka > fi_kostenart.id
Ref: fi_layoutpos.parent > fi_invoice.id
Ref: fi_layoutpos.parent > fi_kv.id
Ref: fi_forecast_note.version_id > fi_forecast.id
Ref: fi_forecast_note.group_id > ze_job.job_id
Ref: fi_forecast_note.group_id > ze_bereich.ber_id
Ref: fi_forecast_note.group_id > ze_kunde.kd_id
Ref: fi_ledger.tenant > in_tenant.id
Ref: fi_lead.client_id > ze_kunde.kd_id
Ref: fi_kv_billdate.kv_id > fi_kv.id
Ref: fi_kv_billdate.invoicepos > fi_invoicepos.id
Ref: fi_kostenart.attr_grp > fi_grp.id
Ref: fi_invoice.exchangerate > fi_exchangerate.id
Ref: fi_invoice.sendema > ze_mitarb.ma_id
Ref: fi_invoice.job > ze_job.job_id
Ref: fi_invoice.kunde > ze_kunde.kd_id
Ref: fi_invoice.bordereau > fi_bordereau.id
Ref: fi_invoice.lieferantid > da_firma.id
Ref: fi_invoice.export > fi_exportjournal.id
Ref: fi_invoice.file > file_base.id
Ref: fi_invoice.tenant > in_tenant.id
Ref: fi_invoice.tenantreceiver > in_tenant.id
Ref: fi_invoice.staffexpense > fi_staffexpense.id
Ref: fi_invoice.canceled_invoice > fi_invoice.id
Ref: fi_invoice.lastmod_by > ze_mitarb.ma_id
Ref: fi_workassignment.kvpos_id > fi_kvpos.id
Ref: fi_kv.defma > ze_mitarb.ma_id
Ref: fi_kv.genma > ze_mitarb.ma_id
Ref: fi_kv.vorlage_category > fi_kv_template_category.id
Ref: fi_kv.jobid > ze_job.job_id
Ref: fi_kv.art > fi_kv_type.id
Ref: fi_kv.tenant > in_tenant.id
Ref: fi_kv.file > in_rate_base.id
Ref: fi_kv.lastmod_by > ze_mitarb.ma_id
Ref: fi_kv.lead > fi_lead.id
Ref: fi_kv.created_by > ze_mitarb.ma_id
Ref: fi_forecast_entry.version_id > fi_forecast.id
Ref: fi_forecast_entry.client_id > ze_kunde.kd_id
Ref: fi_forecast_entry.group_id > ze_kunde.kd_id
Ref: fi_forecast_entry.group_id > ze_bereich.ber_id
Ref: fi_forecast_entry.group_id > ze_job.job_id
Ref: fi_forecast_entry.tenant > in_tenant.id
Ref: fi_forecast_entry.lastmod_by > ze_mitarb.ma_id
Ref: fi_invoicepos.ka > fi_kostenart.id
Ref: fi_invoicepos.kvpos > fi_kvpos.id
Ref: fi_invoicepos.invoice > fi_invoice.id
Ref: fi_invoicepos.bordereau > fi_bordereau.id
Ref: fi_invoicepos.job > ze_job.job_id
Ref: fi_invoicepos.grp > fi_grp.id
Ref: fi_invoicepos.rate > in_rate_base.id
Ref: fi_invoicepos.kvpos_in > fi_kvpos.id
Ref: fi_invoicepos.migrospos > fi_migrospos.id
Ref: fi_invoicepos.taxcode_id > fi_tax_code.id
Ref: fi_invoicepos.account > fi_finance_account.id
Ref: fi_invoicepos.tenant > in_tenant.id
Ref: fi_forecast_confirm.version_id > fi_forecast.id
Ref: fi_forecast_confirm.user_id > ze_mitarb.ma_id
Ref: fi_billing.user > ze_mitarb.ma_id
Ref: fi_billing.invoice > fi_invoice.id
Ref: fi_billing.reference_id > fi_invoice.id
Ref: fi_billing.reference_id > fi_invoicepos.id
Ref: fi_billing.reference_id > fi_purchaseorders.id
Ref: fi_billing.reference_id > te_tender.id
Ref: fi_cost_tenant.cost_id > fi_kostenart.id
Ref: fi_cost_tenant.tenant > in_tenant.id
Ref: fi_budget.cost > fi_kostenart.id
Ref: fi_budget.tenant > in_tenant.id
Ref: fi_bordereau.kunde > ze_kunde.kd_id
Ref: fi_bordereau.ma > ze_mitarb.ma_id
Ref: fi_bordereau.job > ze_job.job_id
Ref: fi_bordereau.tenant > in_tenant.id
Ref: fi_bordereau.file > file_base.id
Ref: fi_bordereau.export > fi_exportjournal.id
Ref: fi_account.tenant > in_tenant.id
Ref: fi_account.fi_kostenart_id > fi_kostenart.id
Ref: comm_attachment.file_id > file_base.id
Ref: edi_migrospos.estimatepos > fi_kvpos.id
Ref: in_numberpattern.tenant > in_tenant.id
Ref: cockpit_lunch_position.employee > ze_mitarb.ma_id
Ref: crm_syncedobject.da_id > ze_mitarb.ma_id
Ref: crm_syncedobject.da_id > da_person.id
Ref: crm_syncedobject.da_id > ze_job.job_id
Ref: crm_syncedobject.da_id > da_firma.id
Ref: crm_syncedobject.sticker > crm_sticker.id
Ref: da_firma.migrosid > fi_migrospos.id
Ref: da_receiver.company_id > da_firma.id
Ref: da_receiver.contact_id > da_person.id
Ref: da_receiver.country_id > da_country.id
Ref: fi_costcentre.tenant > in_tenant.id
Ref: fi_costcentre_cost.cost_id > fi_kostenart.id
Ref: fi_costcentre_cost.account_id > fi_account.id
Ref: fi_dunning_document.invoice > fi_invoice.id
Ref: fi_dunning_document.dunning_level > fi_dunning_level.id
Ref: fi_finance_account.ledger > fi_ledger.id
Ref: fi_forecast_entry_costcategory.version_id > fi_forecast.id
Ref: fi_forecast_entry_costcategory.client_id > ze_kunde.kd_id
Ref: fi_forecast_entry_costcategory.area_id > ze_bereich.ber_id
Ref: fi_forecast_entry_costcategory.task_id > ze_job.job_id
Ref: fi_forecast_entry_costcategory.tenant > in_tenant.id
Ref: fi_imported_invoice.object_id > fi_invoice.id
Ref: fi_invoice.dunninglevel > fi_dunning_level.id
Ref: fi_invoicepos.costcentre > fi_costcentre.id
Ref: fi_invoicepos.related_rate > in_rate_base.id
Ref: fi_kvpos.account > fi_account.id
Ref: fi_kvpos.costcentre > fi_costcentre.id
Ref: fi_kvpos.related_rate > in_rate_base.id
Ref: fi_position_percent.rate > in_rate_base.id
Ref: fi_purchaseorders.phase_id > job_phase.id
Ref: fi_recurring_amount.rate > in_rate_base.id
Ref: fi_recurring_amount_percent.cost > fi_kostenart.id
Ref: fi_recurring_date.layoutpos > fi_layoutpos.id
Ref: file_import.file > file_base.id
Ref: file_import.sender > ze_mitarb.ma_id
Ref: file_import_user.import_id > file_import.id
Ref: file_import_user.user_id > ze_mitarb.ma_id
Ref: comm_mail.sender > da_person.id
Ref: da_companyaccount.paymentcondition_creditor > fi_paymentcondition.id
Ref: da_companyaccount.paymentcondition_debtor > fi_paymentcondition.id
Ref: fi_invoice.created_by > ze_mitarb.ma_id
Ref: fi_recurring_amount.phase_id > job_phase.id
Ref: fi_recurring_amount_rate.baserate > in_rate_base.id
Ref: fi_recurring_amount_rate.stafflevel > in_stafflevel.id
Ref: file_base.job > ze_job.job_id
Ref: in_synclog.user > ze_mitarb.ma_id
Ref: pm_cc.responsible > ze_mitarb.ma_id
Ref: pm_employee_workload.employee > ze_mitarb.ma_id
Ref: pm_workload.job_id > ze_job.job_id
Ref: pm_workload.ma_id > ze_mitarb.ma_id
Ref: sync_event.trigger_user > ze_mitarb.ma_id
Ref: sync_key.tenant_id > in_tenant.id
Ref: sync_queue.trigger_user > ze_mitarb.ma_id
Ref: te_tender.purchase_order_id > fi_purchaseorders.id
Ref: ze_job.jobstatus > job_status.id
Ref: ze_leistg.cost > fi_kostenart.id
Ref: comm_message.thumbnail > file_base.id
Ref: da_firma.image > file_base.id
Ref: da_firma.termofpayment > fi_paymentcondition.id
Ref: da_person.image > file_base.id
Ref: fi_kv.migrosfile > file_base.id
Ref: fi_position_rate_multiplier.unit > fi_leistg_unit.id
Ref: in_content_connection.data_id > ze_kunde.kd_id
Ref: nt_message.payload > nt_payload.id
Ref: sc_orders.estimate > fi_kv.id
Ref: te_document.default_costtype > fi_kostenart.id
Ref: ze_job.remainingbudget > job_remaining_budget.id
Ref: ze_job.remaininghoursbudget > job_remaining_hours_budget.id
Ref: ze_kunde.client_intern > ze_kunde.kd_id
Ref: da_firma.adresse > da_adresse.id
Ref: da_firma.branche > da_branche.id
Ref: da_firma.rechnung > da_adresse.id
Ref: da_firma.zustellen > da_adresse.id
Ref: da_personuser.user > ze_mitarb.ma_id
Ref: da_receiver.address_id > da_adresse.id
Ref: doc_document.duplicationid > doc_document.id
Ref: fi_cost_tenant.tenant_id > in_tenant.id
Ref: fi_dunning_document.file > file_base.id
Ref: fi_forecast_entry_costcategory.cost_id > fi_kostenart.id
Ref: fi_forecast_note.user_id > ze_mitarb.ma_id
Ref: fi_invoicepos.channel_id > crm_channel.id
Ref: fi_invoicepos.phase_id > job_phase.id
Ref: fi_kostenart.category > cal_category.id
Ref: fi_kvpos.channel_id > crm_channel.id
Ref: fi_kvpos.phase_id > job_phase.id
Ref: fi_layoutpos.copyfrom > fi_layoutpos.id
Ref: fi_layoutpos.phase_id > job_phase.id
Ref: fi_ledger.account > fi_finance_account.id
Ref: fi_ledger_entry.account > fi_finance_account.id
Ref: fi_position_rate.unit > fi_leistg_unit.id
Ref: fi_recurring_amount_rate.unit > fi_leistg_unit.id
Ref: fi_recurring_date.recurring_amount > fi_recurring_amount.id
Ref: fi_staffexpense.export > fi_exportjournal.id
Ref: fi_staffexpense.file > file_base.id
Ref: file_import.logfile > file_base.id
Ref: in_content_connection.file_id > file_base.id
Ref: in_datalogged.phaseid > job_phase.id
Ref: in_lock.user_id > ze_mitarb.ma_id
Ref: in_menu_usage.user_id > ze_mitarb.ma_id
Ref: in_tenant.country > da_country.id
Ref: in_tenant.finance_address_id > da_adresse.id
Ref: in_userrolle.rolle > in_rolle.id
Ref: in_userrolle_pending.rolle > in_rolle.id
Ref: pm_workpackages.phase_id > job_phase.id
Ref: te_tender.phase > job_phase.id
Ref: te_tender.template > da_templates.id
Ref: te_tender.rate > in_rate.id
Ref: te_document.template > da_templates.id
Ref: in_rate.agency > in_tenant.id
Ref: fi_budget.id > ze_kunde.kd_id
Ref: fi_budget.id > ze_bereich.ber_id
Ref: fi_budget.id > ze_job.job_id